/**
 * Paints the categorical source PNGs and explicit queue masks from layout.json, then writes
 * fixture-assembled ParkBundles. Usage: npm run content:paint [-- --preview]
 * Deterministic: re-running produces byte-identical outputs (checked by tests).
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';
import { PALETTE, asciiPreview, paintStage, type Layout, type Stage } from './layout-lib';
import { assembleBundle, type ParkContent, type PlaceContent } from './assemble';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fixturesDir = join(root, '..', '..', 'fixtures', 'parks');
const layout = JSON.parse(readFileSync(join(root, 'layout.json'), 'utf8')) as Layout;
const places = (JSON.parse(readFileSync(join(root, 'places.json'), 'utf8')) as { places: PlaceContent[] }).places;
const park = JSON.parse(readFileSync(join(root, 'park.json'), 'utf8')) as ParkContent;
const sha = async (b: Uint8Array) => createHash('sha256').update(b).digest('hex');

export function encodePng(codes: Uint8Array, width: number, height: number): Buffer {
  const png = new PNG({ width, height, colorType: 6, inputHasAlpha: true });
  for (let i = 0; i < codes.length; i++) {
    const rgb = PALETTE[codes[i] as 0 | 1 | 2 | 3 | 4];
    png.data[i * 4] = rgb[0]; png.data[i * 4 + 1] = rgb[1]; png.data[i * 4 + 2] = rgb[2]; png.data[i * 4 + 3] = 255;
  }
  return PNG.sync.write(png, { colorType: 6, deflateLevel: 9 });
}

let failed = false;
for (const stage of [1, 2] as Stage[]) {
  const painted = paintStage(layout, stage);
  const dir = join(root, 'generated', `stage${stage}`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'grid.png'), encodePng(painted.codes, painted.width, painted.height));
  writeFileSync(join(dir, 'queue-zones.json'), JSON.stringify({
    $comment: 'GENERATED by tools/paint.ts from layout.json. cellIndices are row-major (row * width + col), ordered head (service end) to tail (entry).',
    stage, width: painted.width, queueZones: painted.queueZones }, null, 1) + '\n');
  const { bundle, errors } = await assembleBundle(layout, places, park, stage, sha);
  mkdirSync(fixturesDir, { recursive: true });
  writeFileSync(join(fixturesDir, `harbor-lights-stage${stage}.bundle.json`), JSON.stringify(bundle) + '\n');
  // Engine compiler input: everything except the cell bytes, which come from grid.png.
  const { cellsBase64: _c, cellsSha256: _h, encoding: _e, ...gridMeta } = bundle.grid;
  writeFileSync(join(dir, 'metadata.json'), JSON.stringify({ ...bundle, grid: gridMeta }, null, 2) + '\n');
  if (process.argv.includes('--preview')) console.log(asciiPreview(painted, 2));
  console.log(`stage ${stage}: ${bundle.places.length} places, ${bundle.queueZones.length} queue zones, cells sha256 ${bundle.grid.cellsSha256}`);
  if (errors.length) { failed = true; console.error(errors.join('\n')); }
}
if (failed) process.exit(1);
